### ISSUE TITLE
Can set the license in CocConfig but receive undefined for everything else

### ISSUE THREAD

**Issue by bedwardly-down** [voldikss/coc-template#10]
Attached is my CocConfig file and a test source file to show what's going on.
[error.zip](https://github.com/voldikss/coc-template/files/4023503/error.zip)

I'm also running Arch Linux with the latest version of neovim and latest nodejs

**Comment by voldikss** [comment]
Please run `:CocUpdate` try again

**Comment by bedwardly-down** [comment]
Thanks for fixing as quickly as you did. :D
