### ISSUE TITLE
Auto add header while an empty buffer is being created

### ISSUE THREAD

**Issue by yech1990** [voldikss/coc-template#12]
How to make coc-template work in the same way as vim-template?

- [ ] add the template header if the buffer is empty.
- [ ] close without saving if there is nothing new in the file, except the header part.
- [ ] enter insert mode automatically into %HERE% mark.
- [ ] support both user specify templates and system default templates,

**Comment by yech1990** [comment]
Sorry about that, this commit do not fix any of these problems, even those checked ones.

I add an autocmd command following the instruction, but nothing changed either.

**Comment by voldikss** [comment]
That's wierd. At least this `autocmd` `autocmd BufNewFile .gitignore CocCommand template.templateTop` works for me.

**Comment by voldikss** [comment]
> enter insert mode automatically into %HERE% mark.

How about this one? It's simple so I think at least this should work.

**Comment by yech1990** [comment]
I am not 100 percent sure what is going on. If I add template by customized key mapping, which is mapped to (coc-template-top), the buffer is still in nornal mode, but once I hit on any key, the buffer switch to insert mode after this event. The first keystroke can be any text key, but the text will show up just after the second keystroke.

**Comment by yech1990** [comment]
`autocmd BufNewFile` works by chance, but the delay is horrible. I have read all the code in this repo carefully, and tried to fix this problems by myself too. After some simple attempt, I realized it is not easy stuff for coc to achieve this simple job. ...

**Comment by voldikss** [comment]
> but the delay is horrible

Yes that's true. Sadly there is no more space to improve that. Because this extension only runs after coc.nvim startup. Actually I use this just as a rought alternative for vim-template. If you use this functionality very frequently, vim-template might be a better choice.

**Comment by yech1990** [comment]
Sadly, yes, I switch back to vim-template now. Thank you for the time.
